name: AWS Role Test

on:
  push:
    branches:
      - main

jobs:
  aws-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ”‘ Configurar IAM Role con GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          #role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-to-assume: arn:aws:iam::122610492430:role/GitOps_CDKRole
          aws-region: us-east-1

      - name: ğŸ” Probar conexiÃ³n con AWS
        run: |
          if aws sts get-caller-identity; then
            echo "âœ… ConexiÃ³n exitosa a AWS con IAM Role"
          else
            echo "âŒ Error al conectar con AWS"
            exit 1
          fi
